# Official rust image https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

before_script:
 - apt-get update --yes -qq # yqq = yes, very quitely
 - apt-get install -yqq --no-install-recommends cmake llvm-dev libclang-dev clang

test:cargo:
  script:
  - rustc --version && cargo --version
  - cargo test --all --verbose # matrix-style is a possibility too
