# Rust latest
FROM mcr.microsoft.com/devcontainers/rust:latest

# Install Required Dependencies
RUN apt-get -qq update
RUN apt-get install build-essential cmake git libgit2-dev clang libncurses5-dev libncursesw5-dev zlib1g-dev pkg-config libssl-dev llvm
