[package]
name = "grin_integration"
version = "5.5.1-alpha.0"
authors = ["Grin Developers <mimblewimble@lists.launchpad.net>"]
description = "Multi-node integration tests for the Grin node"
license = "Apache-2.0"
repository = "https://github.com/mimblewimble/grin"
keywords = ["crypto", "grin", "mimblewimble"]
workspace = ".."
edition = "2021"
publish = false

[dependencies]
bufstream = "0.1"
futures = "0.3"
log = "0.4"
serde_json = "1"

grin_api = { path = "../api", version = "5.5.1-alpha.0" }
grin_core = { path = "../core", version = "5.5.1-alpha.0" }
grin_p2p = { path = "../p2p", version = "5.5.1-alpha.0" }
grin_servers = { path = "../servers", version = "5.5.1-alpha.0" }
grin_util = { path = "../util", version = "5.5.1-alpha.0" }
