name: Continuous Integration
on: [push, pull_request]

jobs:
  linux-tests:
    name: Linux Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_args: [servers, chain, core, keychain, pool, p2p, src, api, util, store]
    steps:
      - uses: actions/checkout@v3
      - name: Test ${{ matrix.job_args }}
        working-directory: ${{ matrix.job_args }}
        run: cargo test --release

  clippy:
    name: Clippy Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run clippy
        run: cargo clippy --workspace --all-targets -- -D warnings -A clippy::arc_with_non_send_sync -A clippy::double_parens -A clippy::explicit_counter_loop -A clippy::large_enum_variant -A clippy::legacy_numeric_constants -A clippy::manual_flatten -A clippy::manual_try_fold -A clippy::module_inception -A clippy::new_without_default -A clippy::non_canonical_partial_ord_impl -A clippy::redundant_pattern_matching -A clippy::same_item_push -A clippy::should_implement_trait -A clippy::single_component_path_imports -A clippy::single_range_in_vec_init -A clippy::suspicious_open_options -A clippy::too_many_arguments -A clippy::type_complexity -A clippy::unnecessary_mut_passed -A clippy::unnecessary_unwrap -A clippy::useless_conversion -A clippy::vec_init_then_push -A clippy::while_let_loop

  macos-tests:
    name: macOS Tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tests
        run: cargo test --release --all

  windows-tests:
    name: Windows Tests
    runs-on: windows-2022
    env:
      ROARING_ARCH: x86-64-v2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tests
        run: cargo test --release --all

  telegram-notify:
    name: Telegram Notification
    needs: [linux-tests, macos-tests, windows-tests, clippy]
    if: always() && github.event_name == 'push'
    uses: ./.github/workflows/telegram.yaml
    secrets: inherit
    with:
      title: Grin CI
      status: ${{ contains(join(needs.*.result, ','), 'failure') && 'failed' || contains(join(needs.*.result, ','), 'cancelled') && 'cancelled' || 'success' }}
      details: |
        <b>Linux:</b> ${{ needs.linux-tests.result }}
        <b>macOS:</b> ${{ needs.macos-tests.result }}
        <b>Windows:</b> ${{ needs.windows-tests.result }}
        <b>Clippy:</b> ${{ needs.clippy.result }}
      commit_message: ${{ github.event.head_commit.message }}
